name       : fdm-materials
version    : 4.0.0
release    : 4
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.0.0.tar.gz : ab2c6fcbabd699c65380d7746e58d85e8d5d46271b88b13ba325d6b9f1b66f08
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
