name       : fdm-materials
version    : 3.6.0
release    : 3
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/3.6.0.tar.gz : c6c775d4e117f65b7a1d0a0176836c420b601ec9e66f2fec7b4ba5bfed8a60b3
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
