name       : fdm-materials
version    : 4.4.1
release    : 8
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/v4.4.1.tar.gz : 92915f6b39bea142209005ed1916dc0968c17bd64dcde1b4c73a05e698355d7d
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
