name       : fdm-materials
version    : 4.1.0
release    : 5
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.1.0.tar.gz : 4a71742d33f004e6c1b63a25b3c296c2c7872a189775b1dcbaeea9853ec59166
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
