name       : fdm-materials
version    : 4.11.0
release    : 15
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.11.0.tar.gz : ae339f08ffb5bf14f2dadf4e2c374acec3c0a82c7e9b323cf1e50f081dde274f
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
