name       : fdm-materials
version    : 4.13.0
release    : 17
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/refs/tags/4.13.0.tar.gz : 5db128a41437bc7326c440f5f75a09f67cadaefa1e511fa24046be58a3d4a1d8
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
