name       : fdm-materials
version    : 4.6.1
release    : 9
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.6.1.tar.gz : eb7c9cfba1b89b02c447f620df01a919649ffa7c4eaef96f3704829111954b7d
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
