name       : fdm-materials
version    : 4.3.0
release    : 7
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.3.0.tar.gz : b31b997cae18a85f8c913b4d1f0fe0a5a009f94689d4cc26682f6614d0dc3f09
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install