name       : fdm-materials
version    : 4.7.1
release    : 11
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.7.1.tar.gz : f828baf9248ffcb05685980d079db906f2363958aa637255e36719d29d9922c5
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
