name       : fdm-materials
version    : 4.8.0
release    : 12
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.8.0.tar.gz : 1fe1462f60700e08314e24e636eebf3218eb0174db8763cd955ad080c6568f1a
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
