name       : fdm-materials
version    : 4.12.0
release    : 16
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.12.0.tar.gz : f559a5c9a7ca926de1b13fdd6cadb765d0a53b14a2279dbf2782def7b087ec41
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
