name       : fdm-materials
version    : 4.2.0
release    : 6
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.2.0.tar.gz : 96b2946ced9dec98fa73d82644dcaf6ce5801d9d9edc23d3f42b73a76fda0ef3
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
