name       : fdm-materials
version    : 4.9.1
release    : 13
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.9.1.tar.gz : 829f25cfcdcd0e9bd522f67111c049f4a49209dac6f70c9b3f010fa488882385
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
