name       : fdm-materials
version    : 3.5.1
release    : 2
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/3.5.1.tar.gz : f64f5336b8b9145d156c8c4712ff3ebf2fafdb46e7c519f39507e35fc03ae20c
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
