name       : fdm-materials
version    : 4.6.2
release    : 10
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.6.2.tar.gz : de70f8b6395852aec9f2fc5e47ed63c93cc52d9da3183b7f51c1e6337ca40741
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
