name       : fdm-materials
version    : 3.4.1
release    : 1
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/3.4.1.tar.gz : 175f7475e7cd94486041b12cb61990348d50dbb2f0015979509b916eeac4d07f
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
