name       : fdm-materials
version    : 4.10.0
release    : 14
source     :
    - https://github.com/Ultimaker/fdm_materials/archive/4.10.0.tar.gz : 1d516b1a326db9d214125ae882e82ed6ca97881c984d5d2ed7571456082c252b
license    : CC0-1.0
component  : office
summary    : Cura material files
description: |
    Ultimaker FDM Material database.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
